# Generated by Django 4.1.5 on 2023-01-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_01',
            new_name='db01',
        ),
    ]
