# Generated by Django 4.1.5 on 2023-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_db_01_db01'),
    ]

    operations = [
        migrations.AddField(
            model_name='db01',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='db01',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
